### ISSUE TITLE
PowerShell host terminated unexpectedly when opening a solution

### ISSUE THREAD

**Issue by ivanskorikov** [ant-druha/intellij-powershell#155]
Plugin version 2.2, PSES versions 3.11.0 and bundled 1.10.1, Rider version 2023.2

When I open a solution, the PowerShell host process is launched, but terminated with exit code 1 shortly after. As a result, features such as completion are unavailable. 

`idea.log` file contains the following messages:

```
2023-10-02 15:39:26,761 [ 765226]   WARN - #c.i.p.p.l.l.l.EditorServicesLanguageHostStarter - Timed out waiting for session file to appear.
2023-10-02 15:39:26,777 [ 765242]   WARN - #c.i.p.p.l.l.l.LanguageServerEndpoint - Connection creation to PowerShell language host failed for C:/Users/Ivan.Skorikov/RiderProjects/PowerShellExample
2023-10-02 15:39:26,777 [ 765242]   INFO - #c.i.p.p.l.l.l.EditorServicesLanguageHostStarter - PowerShell language host process exited: null
2023-10-02 15:39:26,777 [ 765242]   INFO - #c.i.p.p.l.l.l.LanguageServerEndpoint - Connection to PowerShell language host closed for C:/Users/Ivan.Skorikov/RiderProjects/PowerShellExample.
2023-10-02 15:39:26,808 [ 765273]   INFO - #c.i.p.p.l.l.l.EditorServicesLanguageHostStarter - Language server startup command: '[C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe, -NoProfile, -NonInteractive, C:\Users\Ivan.Skorikov\AppData\Local\Temp\start-pses-host17238674798057839056.ps1]',
 launch command: &("C:\tmp\PSES3.11/PowerShellEditorServices/Start-EditorServices.ps1")  -HostName 'JetBrains Rider' -HostProfileId 'com.intellij.plugin.PowerShell' -HostVersion '2023.2.1' -AdditionalModules @() -BundledModulesPath 'C:\tmp\PSES3.11'  -LogLevel 'Diagnostic' -LogPath 'C:/tmp/PSES3.11/sessions/EditorServices-IJ-1.log' -SessionDetailsPath 'C:/tmp/PSES3.11/sessions/PSES-IJ-1696246766777-session.info' -FeatureFlags @() -SplitInOutPipes
```

[rider-logs-20231002-15503510826217839030380660.zip](https://github.com/ant-druha/intellij-powershell/files/12782369/rider-logs-20231002-15503510826217839030380660.zip)
[Procmon log](https://drive.google.com/file/d/1NNMM6yDFQ6eLCh_O9kEaIo5v1htxwlX1/view?usp=sharing)

**Comment by ForNeVeR** [comment]
```
2023-10-02 15:33:42,710 [ 421175]   WARN - c.i.p.p.l.l.i.s.PowerShellConfigurable - Error detecting PowerShell Editor Services module version: Module manifest file not found: //Mac/Home/Downloads/PowerShellEditorServices.zip/PowerShellEditorServices/PowerShellEditorServices.psd1
com.intellij.plugin.powershell.lang.lsp.languagehost.PowerShellExtensionError: Module manifest file not found: //Mac/Home/Downloads/PowerShellEditorServices.zip/PowerShellEditorServices/PowerShellEditorServices.psd1
	at com.intellij.plugin.powershell.ide.run.PSExecutionUtilKt.getModuleVersion(PSExecutionUtil.kt:28)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.PSLanguageHostUtils.getEditorServicesModuleVersion(PSLanguageHostUtils.kt:75)
	at com.intellij.plugin.powershell.lang.lsp.ide.settings.FormUIUtil.getEditorServicesVersion(FormUIUtil.kt:31)
	at com.intellij.plugin.powershell.lang.lsp.ide.settings.PowerShellConfigurable.apply(PowerShellConfigurable.java:76)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:191)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:322)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:206)
	at com.intellij.openapi.options.newEditor.SettingsEditor.apply(SettingsEditor.java:433)
	at com.intellij.openapi.options.newEditor.SettingsDialog.applyAndClose(SettingsDialog.java:201)
	at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:193)
	at com.jetbrains.rider.settings.RiderSettingsDialog.doOKAction(RiderSettingsDialog.kt:349)
	at com.jetbrains.rider.settings.SaveToAction.actionPerformed(RiderSettingsDialog.kt:369)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.lambda$show$2(Dialog.java:1081)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1041)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:737)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:104)
	at com.jetbrains.rider.settings.RiderShowSettingsUtilImpl.showSettingsDialog(RiderShowSettingsUtilImpl.kt:53)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

This looks like an actual issue: looks like we are unable to detect the PSES version.

What kind of path even is this? Are you aware of this path? What's in your settings actually?

**Comment by ivanskorikov** [comment]
> 2023-10-02 15:33:42,710 [ 421175]   WARN - c.i.p.p.l.l.i.s.PowerShellConfigurable - Error detecting PowerShell Editor Services module version: Module manifest file not found: //Mac/Home/Downloads/PowerShellEditorServices.zip/PowerShellEditorServices/PowerShellEditorServices.psd1

This is me selecting a downloaded PSES zip file instead of the folder I extracted the archive to. Eventually I get it right and the path to PSES is `C:\tmp\PSES3.11/PowerShellEditorServices/Start-EditorServices.ps1`

> What kind of path even is this? Are you aware of this path? What's in your settings actually?

Logs were collected on a Windows 11 ARM64 VM running in Parallels Desktop on a Mac M1. `//Mac/Home/Downloads/` path is something that Parallels mounts in the VM to share files between the host Mac machine and the VM, [details here](https://download.parallels.com/desktop/v12/docs/en_US/Parallels%20Desktop%20User's%20Guide/32922.htm).

**Comment by ivanskorikov** [comment]
Seeing that I can't reproduce this on a Linux or a Mac machine and non-Windows platforms have a different default PS execution policy, I ran `Set-ExecutionPolicy Unrestricted` on the Windows machine and then the behavior changed - `powershell.exe` process that is launched by the plugin is terminated only when I supply a path to the custom PSES services. When I use bundled PSES - `powershell.exe` process is present in the Rider process tree and completion works. This behavior is the same as in #104.

So it appears that the default - `Restricted` - execution policy on Windows prevents launching the language server here.

**Comment by ForNeVeR** [comment]
First, please clarify. Were you trying to run the plugin with custom PSES or not? I expect it to work out of the box without any adjustments and _without_ custom PSES if there's any PowerShell version in the `PATH`.

> Logs were collected on a Windows 11 ARM64 VM running in Parallels Desktop on a Mac M1. `//Mac/Home/Downloads/` path is something that Parallels mounts in the VM to share files between the host Mac machine and the VM

This location is very strange and I believe the path is wrong (it should be `\\Mac\Home\Downloads` instead). Have you entered it manually with a wrong kind of slashes, or did the plugin somehow mangle it?

Anyway, I cannot recommend playing with this kind of file paths for now.

One more thing that comes to my mind is that on Windows, there's also a special lock mode for downloaded binaries. If you downloaded files using a browser, they may become locked by the OS (to prevent accidental execution), and something may break in very weird ways.

But anyway, let's get back to the issue. If I understand correctly, then we are discussing the plugin not being able to start the bundled PSES version, right?

Could you please roll back all these custom PSES experiments and try with the PSES version available in the plugin by default?

**Comment by ivanskorikov** [comment]
> Could you please roll back all these custom PSES experiments and try with the PSES version available in the plugin by default?

Yeah, with the bundled PSES selected, the process starts successfully. I've mentioned this in my previous reply, apologies for not being clear enough:

> _When I use bundled PSES - powershell.exe process is present in the Rider process tree and completion works. This behavior is the same as in https://github.com/ant-druha/intellij-powershell/issues/104._

So, let me reiterate:

1. Bundled PSES, execution policy = default (`Restricted`) => powershell.exe fails to start properly
2. Bundled PSES, execution policy = `Unrestricted` \ `Bypass` => powershell.exe starts successfully, plugin is fully functional
3. Custom PSES, execution policy doesn't matter => powershell.exe fails to start properly.

I think the scenario no. 1 is also problematic, the user shouldn't have to degrade the security of their system in order to use the plugin.

=============================================

> One more thing that comes to my mind is that on Windows, there's also a special lock mode for downloaded binaries. If you downloaded files using a browser, they may become locked by the OS (to prevent accidental execution), and something may break in very weird ways.

As far as I understand, Windows uses an alternate NTFS stream [Zone.Identifier](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/6e3f7352-d11c-4d76-8c39-2516a9df36e8) to keep track of whether the file was downloaded from the internet. In this case it doesn't seem relevant. The only thing downloaded here is the PSES archive, and neither of the files Rider launches has the `Zone.Identifier` stream:
<img width="897" alt="image" src="https://github.com/ant-druha/intellij-powershell/assets/2564318/a215674d-8117-45a3-9f81-8f82ea9f4fa2">

==============================================

> This location is very strange and I believe the path is wrong (it should be \\Mac\Home\Downloads instead). Have you entered it manually with a wrong kind of slashes, or did the plugin somehow mangle it?

Yeah, most likely it was a copy and paste issue. I've tried selecting the PSES folder in this location manually using the file browser opened from the plugin settings page: it inserted the correct path into the text field, and then no `PowerShellExtensionError` was thrown when loading the language server. However, it still failed to start properly with `#c.i.p.p.l.l.l.EditorServicesLanguageHostStarter - PowerShell language host process exited: null`

> Anyway, I cannot recommend playing with this kind of file paths for now.

Ok, I moved PSES folder to `c:\tmp` after the initial failure to read from the mounted Downloads folder.

**Comment by ForNeVeR** [comment]
Alright. So, the issue we investigate here is that with the default security policy and bundled PSES, the plugin is unable to work, right?

Because the issue with not bundled PSES is investigated as #104.

**Comment by ivanskorikov** [comment]
Yes, I think that we can safely assume that problem described #104 and powershell host not starting with custom PSES is the same issue and we should investigate it in #104.

This leaves the problem with bundled PSES not starting with the default execution policy. I can venture a guess that any version of PSES is affected by this, but since #104 is still open I can't verify this hypothesis.
