### ISSUE TITLE
Plugin 'com.intellij.plugin.adernov.powershell' failed to initialize

### ISSUE THREAD

**Issue by tek0011** [ant-druha/intellij-powershell#18]
```
Plugin 'com.intellij.plugin.adernov.powershell' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AbstractMethodError: Method com/intellij/plugin/powershell/lang/lsp/LSPInitMain.getComponentName()Ljava/lang/String; is abstract
    at com.intellij.plugin.powershell.lang.lsp.LSPInitMain.getComponentName(LSPInitMain.kt)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

After installing the plugin and attempting to launch IJ.   

```
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
Licensed to Dell, Inc. / Jeff Sparrow
You have a perpetual fallback license for this version
Subscription is active until April 21, 2020
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

**Comment by ForNeVeR** [comment]
I assume this is a relict of the past, when `NamedComponent::getName` was still an abstract method. Here's [an IntelliJ Community commit that fixed the issue](https://github.com/JetBrains/intellij-community/commit/2a7782d8d8094b2a01dddbb6da0e78037d4528c8). That commit made it into 2017.2 (somewhere around IntelliJ 172.2465).

The latest plugin version still formally supporting IDEA 2017.1.5, intellij-powershell 1.0.2, was in fact built against IDEA 2017.3, and thus there was no compilation error, and it was released in this state, with no implementation for `NamedComponent::getName`.

I am closing this as fixed in intellij-powershell 1.1.0 when the formal compatibility range was lifted up to `172.4574`.

(Also, nowadays we are trying to get more compatibility checks to not break older IDE versions.)
