### ISSUE TITLE
Fatal Error exception in plugin PowerShell(2.0.6) for aarch64-MacOSX

### ISSUE THREAD

**Issue by andrzejkr** [ant-druha/intellij-powershell#62]
java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.EditorServicesLanguageHostStarter.establishConnection(EditorServicesLanguageHostStarter.kt:142)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.scheduleStart(LanguageServerEndpoint.kt:250)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.checkStarted(LanguageServerEndpoint.kt:219)
	at com.intellij.plugin.powershell.lang.lsp.languagehost.LanguageServerEndpoint.connectEditor(LanguageServerEndpoint.kt:114)
	at com.intellij.plugin.powershell.lang.lsp.LSPInitMain$Companion$editorOpened$1.run(LSPInitMain.kt:97)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
	... 18 more
Caused by: java.lang.RuntimeException: Unhandled architecture/OS: aarch64-MacOSX
	at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:30)
	... 23 more

**Comment by ant-druha** [comment]
The macOS ARM support has been recently added to `junixsocket` 2.3.3 version: https://github.com/kohlschutter/junixsocket/issues/88. Will need to update it and test.

**Comment by ant-druha** [comment]
Fixed in 2.0.7 version.
