### ISSUE TITLE
Can't open files anymore in WebStorm 2021.3

### ISSUE THREAD

**Issue by Primajin** [ant-druha/intellij-powershell#78]
When I have this plugin enabled in WebStorm 2021.3 I can not open a single file anymore by double clicking on them in the left side project panel. Worked fine in earlier versions and when disabling this plugin 🤷🏻‍♂️

**Comment by topia** [comment]
EDIT: My problem seems to be #77, I found I can open a file with PowerShell plugin 2.0.7.

same on GoLand 2021.3 EAP.
stacktrace:
<details>

```
Cannot init toolwindow com.intellij.notification.EventLogToolWindowFactory@1ee0d50

java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.registerSettingsPageProvider(LanguageCodeStyleSettingsProvider.java:405)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.calcSettingPagesProviders(LanguageCodeStyleSettingsProvider.java:386)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.lambda$getSettingsPagesProviders$2(LanguageCodeStyleSettingsProvider.java:379)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
	at com.intellij.psi.codeStyle.LanguageCodeStyleSettingsProvider.getSettingsPagesProviders(LanguageCodeStyleSettingsProvider.java:379)
	at com.intellij.psi.codeStyle.CodeStyleSettingsServiceImpl.getCustomCodeStyleSettingsFactories(CodeStyleSettingsServiceImpl.java:64)
	at com.intellij.psi.codeStyle.CustomCodeStyleSettingsManager.initCustomSettings(CustomCodeStyleSettingsManager.java:25)
	at com.intellij.psi.codeStyle.CodeStyleSettings.<init>(CodeStyleSettings.java:101)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.createSettings(CodeStyleSettingsManager.java:52)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.setMainProjectCodeStyle(ProjectCodeStyleSettingsManager.java:79)
	at com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager.<init>(ProjectCodeStyleSettingsManager.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:102)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:57)
	at com.intellij.openapi.editor.impl.SettingsImpl.getTabSize(SettingsImpl.java:389)
	at com.intellij.openapi.editor.ex.util.EditorUtil.getTabSize(EditorUtil.java:336)
	at com.intellij.openapi.editor.impl.view.EditorView.getTabSize(EditorView.java:580)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.reset(LogicalPositionCache.java:75)
	at com.intellij.openapi.editor.impl.view.EditorView.reinitSettings(EditorView.java:366)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:494)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:203)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:173)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:52)
	at com.intellij.notification.EventLogConsole.<init>(EventLogConsole.java:71)
	at com.intellij.notification.EventLog$ProjectTracker.createNewContent(EventLog.java:639)
	at com.intellij.notification.EventLog$ProjectTracker.initDefaultContent(EventLog.java:526)
	at com.intellij.notification.EventLogToolWindowFactory.createToolWindowContent(EventLogToolWindowFactory.java:46)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:542)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:521)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1033)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:979)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:968)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:1110)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:532)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpenedTask$1.run(ToolWindowManagerImpl.kt:448)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.application.options.IndentOptionsEditorBase PluginClassLoader(plugin=PluginDescriptor(name=PowerShell, id=com.intellij.plugin.adernov.powershell, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\Goland\ch-0\213.6206.plugins\PowerShell, version=2.0.8, package=null, isBundled=false), packagePrefix=null, instanceId=43, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 84 more
```

</details>

Build version:

````
GoLand 2021.3 EAP
Build #GO-213.6206, built on November 30, 2021
````

**Comment by ant-druha** [comment]
Uploaded new plugin version: https://plugins.jetbrains.com/plugin/10249-powershell/versions/stable/147932

There was an API change that made the plugin incompatible with 2021.3 IDE versions: https://youtrack.jetbrains.com/issue/IDEA-281472

2.0.9 version should be working now. Please try. Thank you.

**Comment by topia** [comment]
@ant-druha Thanks! I confirmed that 2.0.9 is working too.

**Comment by Primajin** [comment]
Wow that was fast, thanks a lot 👍🏻
